create table if not exists public.complaints (
  id bigint generated by default as identity primary key,
  ticket_number text not null unique,
  name text not null check (char_length(name) between 2 and 80),
  whatsapp text not null check (char_length(whatsapp) between 9 and 16),
  environment text not null check (char_length(environment) <= 60),
  category text not null check (category in ('Jalan', 'Sampah', 'Drainase', 'Air', 'Lampu jalan', 'Fasilitas publik', 'Keamanan', 'Lainnya')),
  location text not null check (char_length(location) <= 160),
  description text not null check (char_length(description) between 10 and 1500),
  status text not null default 'Baru' check (status in ('Baru', 'Diproses', 'Selesai')),
  created_at timestamptz not null default now()
);

alter table public.complaints enable row level security;

revoke all on table public.complaints from anon, authenticated;
