create table if not exists public.officials (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 100),
  position text not null check (position in ('Lurah', 'Sekretaris', 'Kepala Seksi Pemerintahan, Ketenteraman dan Ketertiban', 'Kepala Seksi Pembangunan dan Keuangan', 'Kepala Seksi Kesejahteraan Rakyat', 'Kepala Lingkungan', 'Wakil Kepala Lingkungan')),
  lingkungan integer not null default 0 check (lingkungan between 0 and 20),
  sort_order integer not null default 0 check (sort_order between 0 and 999),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists officials_public_idx
  on public.officials(active, lingkungan, sort_order);

drop trigger if exists officials_touch on public.officials;
create trigger officials_touch before insert or update on public.officials
  for each row execute function public.touch_content_row();

alter table public.officials enable row level security;

revoke all on table public.officials from anon, authenticated;
grant select on table public.officials to anon;
grant select, insert, update, delete on table public.officials to authenticated;

drop policy if exists "public_read_officials" on public.officials;
create policy "public_read_officials" on public.officials
  for select to anon, authenticated using (active = true);

drop policy if exists "operators_manage_officials" on public.officials;
create policy "operators_manage_officials" on public.officials
  for all to authenticated using (public.is_operator()) with check (public.is_operator());

-- Seed from the "Susunan Organisasi Kelurahan Taratara Dua" board, only when the table is empty.
insert into public.officials (name, position, lingkungan, sort_order)
select * from (values
  ('Ebenhaezer A. R. Rares, SE', 'Lurah', 0, 10),
  ('Roy S. Onibala, SE', 'Sekretaris', 0, 20),
  ('Hanny Loho, S.Sos', 'Kepala Seksi Pembangunan dan Keuangan', 0, 30),
  ('Anita Salung', 'Kepala Lingkungan', 1, 40),
  ('Marthen Pongoh', 'Wakil Kepala Lingkungan', 1, 50),
  ('Debby Rawung', 'Kepala Lingkungan', 2, 60),
  ('Daniel Sambeka', 'Wakil Kepala Lingkungan', 2, 70),
  ('Rolly Rares', 'Kepala Lingkungan', 3, 80),
  ('Lexi Wewengkang', 'Wakil Kepala Lingkungan', 3, 90),
  ('Rocky Rumagit', 'Kepala Lingkungan', 4, 100),
  ('Yulce Salea', 'Wakil Kepala Lingkungan', 4, 110),
  ('Victor Mende', 'Kepala Lingkungan', 5, 120),
  ('Lucky Pandey', 'Wakil Kepala Lingkungan', 5, 130),
  ('Verry Poluan', 'Kepala Lingkungan', 6, 140),
  ('Marce Lapong', 'Wakil Kepala Lingkungan', 6, 150),
  ('Adri David', 'Kepala Lingkungan', 7, 160),
  ('Areyne Kandow', 'Wakil Kepala Lingkungan', 7, 170),
  ('Jeanet Wewengkang', 'Kepala Lingkungan', 8, 180),
  ('Djoni Sambow', 'Wakil Kepala Lingkungan', 8, 190)
) as seed(name, position, lingkungan, sort_order)
where not exists (select 1 from public.officials);
