alter table public.complaints
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.operator_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 80),
  role text not null default 'operator' check (role in ('admin', 'operator')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.complaint_events (
  id bigint generated by default as identity primary key,
  complaint_id bigint not null references public.complaints(id) on delete cascade,
  operator_id uuid not null references auth.users(id),
  previous_status text not null,
  new_status text not null,
  created_at timestamptz not null default now()
);

create index if not exists complaints_status_created_at_idx
  on public.complaints(status, created_at desc);

create index if not exists complaint_events_complaint_id_idx
  on public.complaint_events(complaint_id, created_at desc);

alter table public.operator_profiles enable row level security;
alter table public.complaint_events enable row level security;

revoke all on table public.operator_profiles from anon, authenticated;
revoke all on table public.complaint_events from anon, authenticated;

grant select on table public.operator_profiles to authenticated;
grant select on table public.complaints to authenticated;
grant update(status) on table public.complaints to authenticated;
grant select on table public.complaint_events to authenticated;

create or replace function public.is_operator()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.operator_profiles
    where id = auth.uid() and active = true
  );
$$;

revoke all on function public.is_operator() from public, anon;
grant execute on function public.is_operator() to authenticated;

drop policy if exists "operator_profiles_read_self" on public.operator_profiles;
create policy "operator_profiles_read_self"
  on public.operator_profiles
  for select
  to authenticated
  using (id = auth.uid() and active = true);

drop policy if exists "operators_read_complaints" on public.complaints;
create policy "operators_read_complaints"
  on public.complaints
  for select
  to authenticated
  using (public.is_operator());

drop policy if exists "operators_update_complaint_status" on public.complaints;
create policy "operators_update_complaint_status"
  on public.complaints
  for update
  to authenticated
  using (public.is_operator())
  with check (public.is_operator());

drop policy if exists "operators_read_complaint_events" on public.complaint_events;
create policy "operators_read_complaint_events"
  on public.complaint_events
  for select
  to authenticated
  using (public.is_operator());

create or replace function public.log_complaint_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status is distinct from old.status then
    new.updated_at = now();
    insert into public.complaint_events (
      complaint_id,
      operator_id,
      previous_status,
      new_status
    ) values (
      old.id,
      auth.uid(),
      old.status,
      new.status
    );
  end if;

  return new;
end;
$$;

revoke all on function public.log_complaint_status_change() from public, anon, authenticated;

drop trigger if exists complaint_status_audit on public.complaints;
create trigger complaint_status_audit
  before update of status on public.complaints
  for each row
  execute function public.log_complaint_status_change();
