create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 3 and 140),
  category text not null check (category in ('Pengumuman', 'Agenda', 'Pelayanan', 'Kegiatan')),
  summary text not null check (char_length(summary) between 10 and 300),
  body text check (char_length(body) <= 5000),
  event_date date,
  status text not null default 'Draft' check (status in ('Draft', 'Terbit', 'Arsip')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 3 and 100),
  description text not null check (char_length(description) between 10 and 300),
  requirements text check (char_length(requirements) <= 2000),
  steps text check (char_length(steps) <= 2000),
  duration text check (char_length(duration) <= 60),
  fee text check (char_length(fee) <= 60),
  sort_order integer not null default 0 check (sort_order between 0 and 999),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.businesses (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 100),
  category text not null check (char_length(category) between 2 and 60),
  product text check (char_length(product) <= 100),
  description text not null check (char_length(description) between 10 and 400),
  whatsapp text check (whatsapp ~ '^\+?[0-9]{9,15}$'),
  address text check (char_length(address) <= 160),
  map_url text check (map_url ~ '^https://' and char_length(map_url) <= 300),
  social_url text check (social_url ~ '^https://' and char_length(social_url) <= 300),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists announcements_public_idx
  on public.announcements(status, published_at desc);
create index if not exists services_public_idx
  on public.services(active, sort_order);
create index if not exists businesses_public_idx
  on public.businesses(active, created_at desc);

create or replace function public.touch_content_row()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  if tg_table_name = 'announcements' then
    if new.status = 'Terbit' and (tg_op = 'INSERT' or old.status is distinct from 'Terbit') then
      new.published_at = now();
    end if;
  end if;
  return new;
end;
$$;

revoke all on function public.touch_content_row() from public, anon, authenticated;

drop trigger if exists announcements_touch on public.announcements;
create trigger announcements_touch before insert or update on public.announcements
  for each row execute function public.touch_content_row();
drop trigger if exists services_touch on public.services;
create trigger services_touch before insert or update on public.services
  for each row execute function public.touch_content_row();
drop trigger if exists businesses_touch on public.businesses;
create trigger businesses_touch before insert or update on public.businesses
  for each row execute function public.touch_content_row();

alter table public.announcements enable row level security;
alter table public.services enable row level security;
alter table public.businesses enable row level security;

revoke all on table public.announcements, public.services, public.businesses from anon, authenticated;
grant select on table public.announcements, public.services, public.businesses to anon;
grant select, insert, update, delete on table public.announcements, public.services, public.businesses to authenticated;

-- Public visitors only see published or active rows.
drop policy if exists "public_read_announcements" on public.announcements;
create policy "public_read_announcements" on public.announcements
  for select to anon, authenticated using (status = 'Terbit');

drop policy if exists "public_read_services" on public.services;
create policy "public_read_services" on public.services
  for select to anon, authenticated using (active = true);

drop policy if exists "public_read_businesses" on public.businesses;
create policy "public_read_businesses" on public.businesses
  for select to anon, authenticated using (active = true);

-- Active operators manage every row, including drafts and hidden entries.
drop policy if exists "operators_manage_announcements" on public.announcements;
create policy "operators_manage_announcements" on public.announcements
  for all to authenticated using (public.is_operator()) with check (public.is_operator());

drop policy if exists "operators_manage_services" on public.services;
create policy "operators_manage_services" on public.services
  for all to authenticated using (public.is_operator()) with check (public.is_operator());

drop policy if exists "operators_manage_businesses" on public.businesses;
create policy "operators_manage_businesses" on public.businesses
  for all to authenticated using (public.is_operator()) with check (public.is_operator());
